### ISSUE TITLE
Error in console, "There is no route for the path: "

### ISSUE THREAD

**Issue by talha-asad** [VeliovGroup/Meteor-flow-router-meta#1]
Every route i visit i get this error in the console. Any idea what i may be doing wrong, i checked the paths are loaded before i initialize `FlowRouterMeta` and `FlowRouterTitle`

**Comment by dr-dimitru** [comment]
Could you please post your Router Map code?

**Comment by talha-asad** [comment]
What is a Router Map?

**Comment by dr-dimitru** [comment]
> What is a Router Map?

All registered routers, and just to make sure, we're laking about `flow-router-extra` right?

**Comment by talha-asad** [comment]
Yes, below are some of the routes, they seem to work fine with `flow-router` but give error with `flow-router-extra`

``` js
AppRoutes = FlowRouter.group({
  name: 'AppRoutingGroup',
  prefix: '/app',
  layout: 'app_layout',
  link: {
    icon: {
      rel: 'icon',
      type: 'image/x-icon',
      href: '/favicon.ico',
      sizes: '16x16 32x32 48x48 72x72 96x96'
    }
  }
});

AppRoutes.route('/', {
  name: 'app-overview',
  template: 'app_overview',
  action() {
    BlazeLayout.render(this.options.layout ? this.options.layout : this.group.options.layout, {
      template: this.options.template
    });
  }
});

/*
---
------ Analytics
---
*/

AppRoutes.route('/analytics', {
  name: 'app-analytics',
  template: 'app_analytics',
  action() {
    BlazeLayout.render(this.options.layout ? this.options.layout : this.group.options.layout, {
      template: this.options.template
    });
  }
});
```

**Comment by dr-dimitru** [comment]
1. With path are you trying to visit?
2. Which packages is installed? Could you post content of `.meteor/packages`?
3. Why are you using `BlazeLayout.render` ? `FlowRouter-Extra` has build-in render

**Comment by talha-asad** [comment]
1. I try visiting `http://localhost:3000/app`
2. `.meteor/packages` below:

```
meteor-base             # Packages every Meteor app needs to have
mobile-experience       # Packages for a great mobile UX
mongo                   # The database Meteor supports right now
session                 # Client-side reactive dictionary for your app
jquery                  # Helpful client-side library
tracker                 # Meteor's client-side reactive programming library

es5-shim                # ECMAScript 5 compatibility for older browsers.
ecmascript              # Enable ECMAScript2015+ syntax in app code

reactive-var
reactive-dict
check
http
email
xamfoo:reactive-obj
u2622:persistent-session

service-configuration
accounts-twitter
accounts-google
accounts-facebook

templating
mquandalle:jade
semantic:ui
flemay:less-autoprefixer


ostrio:flow-router-extra
ostrio:flow-router-meta
kadira:blaze-layout
arillo:flow-router-helpers
zimme:active-route
lookback:body-class
tomwasd:flow-router-autoscroll

momentjs:moment
mrt:moment-timezone

dburles:google-maps
jeremy:geocomplete
jesty:polyline

cfs:standard-packages
cfs:filesystem

mnmtanish:call
ostrio:meteor-root

schiller:twit
fallentech:twitter-ads

fallentech:numscale
fallentech:timeago

meteorhacks:aggregate

timbrandin:slick
peerlibrary:async@1.5.2_1
gorillastack:c3
standard-minifier-css
standard-minifier-js
jagi:astronomy
jagi:astronomy-timestamp-behavior
kadira:dochead
philippspo:momentum-flow-router
```
1. Is it necessary to use that? I would like to keep the project still compatible with FlowRouter if I choose to revert. What benefit does that renderer have over `BlazeLayout.render`. I don't think this issue can be a caused due to this.

**Comment by dr-dimitru** [comment]
1. What if you will visit `http://localhost:3000/app/` (_the trailing slash_)?
2. Try to comment out and run without next packages: `philippspo:momentum-flow-router`, `tomwasd:flow-router-autoscroll`
3. No it's not necessary, you can use whatever you want, it was just my suggestion

BTW `arillo:flow-router-helpers` is well tested within `flow-router-extra`

**Comment by talha-asad** [comment]
I'll try these suggestions, might take a bit of time. In the meanwhile, is there a particular reason why `Flow-router-extra` would require a trailing slash and `flow-router` would not?

**Comment by dr-dimitru** [comment]
No reason for it, just ask to try. Actually I have no idea why this happening to you. I can't reproduce it. Could you also post full error stack?

**Comment by talha-asad** [comment]
Will sure do, thanks!

**Comment by dr-dimitru** [comment]
@talha-asad any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence
