### ISSUE TITLE
Meta tags don't work for social sharing

### ISSUE THREAD

**Issue by dcantatore** [VeliovGroup/Meteor-flow-router-meta#12]
### I have a suggestion:
 I just went and used the dynamic meta tags for the first time and realized they will never be used any social media since they are client side rendered. 

Is there a way to get these tags to be used by social sharing sites?

**Comment by dr-dimitru** [comment]
Hello @dcantatore ,

This is related to Meteor/Blaze/React/JavaScript-powered websites in general, and not something what can be done on package level.
You need to implement SSR (server side rendering), or use "pre-rendering" service, like prerendering.com

**Comment by dcantatore** [comment]
Thanks for the fast reply. Is there a usage for these tags if that is the case - for social?

**Comment by dr-dimitru** [comment]
Yes, you can test veliovgroup.com and cssbuilder.veliovgroup.com for example, which is powered by this package + ostr.io

**Comment by dcantatore** [comment]
Is there any way to use something like:

```<meta name="fragment" content="!">```

To let sites know it's a web app and more data is coming? The to have it use a before hook to send the data?

Paying for pre-render seems like a last resort.

**Comment by dr-dimitru** [comment]
So far `<meta name="fragment" content="!">` is officially deprecated feature by Google, but I'd still recommend to use it as other crawlers may still use this feature.

DISCLAIMER: Details below provided according to my tests and knowledge

 - Speaking of social networks — none of social networks would execute JS in order to fetch meta-tags.
 - Speaking of Google — It may or may not execute JS to fetch its content and meta-tags. How decision made?  — No one knows
 - Speaking of other search engines — Most of what I've tested (TOP 10 by usage worldwide) none of them executing JS in order to pull website's data

Hope that helps, let me know if you will find different information.

**Comment by dcantatore** [comment]
Ok, I'm currently looking into the server-rendering package and see if that it is another way to achieve my goal. No examples of how to use with blaze so I'll see what I can work out. Thanks for all your help.

https://docs.meteor.com/packages/server-render.html

**Comment by dr-dimitru** [comment]
@dcantatore let's keep this thread open. Please, update it with your final solution, I believe other folks will find use in it as well

**Comment by dcantatore** [comment]
Will do, I think it might involve a solution outside of using flow-router-meta but I will include it either way.

**Comment by dcantatore** [comment]
Alright, I got a solution but it is not using this package at all. I think there could be some potential to make a PR to somehow tie this into the package but we can discuss that after you see the solution. Here is what the code looks like as used and working on my site:

```
import { onPageLoad } from 'meteor/server-render';
import { CollectionName} from '../lib/databases';

onPageLoad(sink => {
    if (sink && sink.request && sink.request.url) {
        let pathName = '';
        if (sink.request.url.pathname) {
            pathName = sink.request.url.pathname;
        }

        if (pathName === '/pathForDynamicMetaHere') {
            if (sink.request.url.query.queryParameterThatIGetDataBasedOn) {
                const nameOfParam= sink.request.url.query.nameOfParam;
                const doc= CollectionName.findOne({ _id: nameOfParam});
                if (doc) {
                    sink.appendToHead(`
<meta property="og:title" content="Words Here ${doc.name}">
<meta property="og:description" content="${doc.moreStuff}">
<meta property="og:image" content="${checksToMakeSureImageExists ? `https://website.com/images/backgrounds/${doc._id}/${doc.images.background.cover}` : `${siteImageVariableThatIImportForGeneric}`}">
  `);
                }
            }
        } else if (pathName !== '/annouce' && pathName !== '/scrape') { // these are ones that meteor polls on a regular basis while sitting on site so ignore those and otherwise serve generic meta
            sink.appendToHead(`
<meta property="og:title" content="Title Stuff">
<meta property="og:description" content="Content Stuff">
<meta property="og:image" content="imgUrl">`);
        }
    }
});
```

**Comment by dr-dimitru** [comment]
@dcantatore great solution. Using `meteor/server-render` falls into SSR category.

A few notes on pre-rendering service vs. SSR — Implementing SSR requires time and extra efforts from a development team. If we are speaking business-wise, it adds additional complexity and extra development hours. While pre-rendering cost might be below $10/mo., a single development+QA hour can cover a year of pre-rendering of an average web application.

So, this is more about choosing the right technology/tool/approach to solve a particular task while keeping a balance between quality and cost-efficiency.

Pre-rendering services and its teams spend years to achieve the best SEO score for its clients, so it might (or not) worth it.

**Comment by dcantatore** [comment]
I fully agree. 

Maybe this is its own package for easy meta for people that need this niche part of meta pre-rendered in a basic way.  What's your thoughts on spinning something like that up real quick with me/other people?

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
