### ISSUE TITLE
 going to localhost:3000/packages/jquery.js displays a file.

### ISSUE THREAD

**Issue by nikhilgoswami** [VeliovGroup/Meteor-flow-router-meta#14]
### I'm having an issue:
  I don't know the issue is related to this package but on meteor project going to localhost:3000/packages/jquery.js displays a file.
  - Version of `Meteor`  1.10.2
  - Browser name and its version all
  - Platform name and its version  Ubuntu not tested others
test url  https://vapt.ecobillz.com/app/packages/jquery.js

### I have a suggestion:

Disable source map access through routes

**Comment by dr-dimitru** [comment]
I'm pretty sure I've answered exactly the same question on the other repo.
Closing as duplicate
