### ISSUE TITLE
FlowRouter: Redirect to subdomain w/o page refresh? 

### ISSUE THREAD

**Issue by drone1** [VeliovGroup/Meteor-flow-router-meta#15]
Anyone know if this is possible? Users are able to create pages on subdomains of my app's domain and my `<a>` tags cause the site to refresh. Any suggestions?

It's critical for my app, which has an audio player which can't be disrupted by transitioning from subdomain to subdomain. 

Thanks for any help!

**Comment by dr-dimitru** [comment]
No, History API prohibit this by design
