### ISSUE TITLE
Flowrouter route group support

### ISSUE THREAD

**Issue by talha-asad** [VeliovGroup/Meteor-flow-router-meta#2]
Seems it doesn't register routes if they are added in a FlowRouter group.

**Comment by dr-dimitru** [comment]
Have you seen [this lines](https://github.com/VeliovGroup/Meteor-flow-router-meta/blob/master/demo/client/routes.coffee#L57) in demo app?

**Comment by talha-asad** [comment]
Did you test them on the latest flow-router and meteor versions?

**Comment by dr-dimitru** [comment]
Do you mean `flow-router-extra`, right?

**Comment by talha-asad** [comment]
Yes.

**Comment by talha-asad** [comment]
I think this is one and the same issue as #1

**Comment by dr-dimitru** [comment]
> Did you test them on the latest flow-router and meteor versions?

Yes, I'm using it daily
