### ISSUE TITLE
FlowRouterMeta is not defined

### ISSUE THREAD

**Issue by oliverwebr** [VeliovGroup/Meteor-flow-router-meta#3]
I initialised FlowRouterMeta and FlowRouterTitle like this:

new FlowRouterMeta(FlowRouter);
new FlowRouterTitle(FlowRouter);

at the end of my routes.js but still get a error log:

```
W20161019-03:57:57.510(2)? (STDERR)
W20161019-03:57:57.511(2)? (STDERR) ReferenceError: FlowRouterTitle is not defined
W20161019-03:57:57.511(2)? (STDERR)     at meteorInstall.lib.routes.js (lib/routes.js:96:5)
W20161019-03:57:57.511(2)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
```

Packages:
meteor-base@1.0.4  
mobile-experience@1.0.4  
mongo@1.1.12_1  
blaze-html-templates@1.0.4  
reactive-var@1.0.10  
tracker@1.1.0                 

standard-minifier-css@1.2.0_1  
standard-minifier-js@1.2.0_1  
es5-shim@4.6.14_1  
ecmascript@0.5.8_1              

shell-server@0.2.1
aldeed:simple-schema
session@1.1.6
meteortoys:allthings

jquery@1.11.9

ostrio:files
ostrio:flow-router-extra
ostrio:flow-router-title
ostrio:flow-router-meta

kadira:blaze-layout
accounts-ui@1.1.9
accounts-password@1.3.0

**Comment by dr-dimitru** [comment]
It should be done on _Client_ only. It's _Client_ only libs

**Comment by dr-dimitru** [comment]
Please, support this project by:
- Star on [GitHub](https://github.com/VeliovGroup/Meteor-flow-router-meta)
- Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-meta)
