### ISSUE TITLE
[Question] Is the package production ready ?

### ISSUE THREAD

**Issue by gurjit03** [VeliovGroup/Meteor-flow-router-meta#4]
I was searching from sometime for any package to add meta, title tags for flowRouter. Most of the packages I encounter was usually for Iron:router, and finally found this package. So the obv. question that raises, is this package production ready ?

**Comment by dr-dimitru** [comment]
Hello @gurjit03 ,

Yes, we are using it in our projects for at least 1.5 years.
We regularly update it, adding new features and fixing bugs.

See [FR-Extra](https://github.com/VeliovGroup/flow-router) for more info

**Comment by gurjit03** [comment]
@dr-dimitru Thanks alot :+1:

**Comment by dr-dimitru** [comment]
Feel free to reopen if you have more questions
