### ISSUE TITLE
Reactive content()

### ISSUE THREAD

**Issue by nicooprat** [VeliovGroup/Meteor-flow-router-meta#6]
Following the discussion here: https://github.com/VeliovGroup/Meteor-flow-router-title/issues/9

Would be great to have `content()` reactive for metas too.

```js
allRoutes.route('/:storyId', {
  meta: {
    'og:image': {
      property: 'og:image',
      content({storyId}) {
       // Not reactive
        const story = story && Stories.find(storyId).fetch()[0]    
        return story && story.title
      }
    },
  },
}
```

I also tried to use the `data` hook:

```js
allRoutes.route('/:storyId', {
  data({username, storyId, storySlug, chapterId, chapterSlug}) {
    // Not reactive
    const story = story && Stories.find(storyId).fetch()[0]    
    return story
  },
  meta: {
    'og:image': {
      property: 'og:image',
      content(params, query, story) {
        // Runs only once
        return story && story.getPath()
      }
    },
  },
}
```

Actually my goal is to make all this routes compatible with https://github.com/VeliovGroup/jazeee-meteor-spiderable. I have to set `Meteor.isReadyForSpiderable = true` when all the metas are  correctly set for crawlers from Google, Facebook, ... I might have missed something obvious to make all of this simpler, as I see that I'll have the same issue the new `innerHTML` feature: https://github.com/VeliovGroup/Meteor-flow-router-meta#ldjson. 

Any advice? :)

**Comment by dr-dimitru** [comment]
> Any advice? :)

Yes, [wait for the data](https://github.com/VeliovGroup/flow-router#waiton-hook).
I have no plans to make it reactive, it will be overkill for performance.
And [waitOn](https://github.com/VeliovGroup/flow-router#waiton-hook) is the reason to make your day simpler.

**Comment by dr-dimitru** [comment]
> Actually my goal is to make all this routes compatible with https://github.com/VeliovGroup/jazeee-meteor-spiderable.

Try [ostr.io](https://ostr.io/info/prerendering) we have made it smart enough to work without hints although [it's recommended](https://github.com/VeliovGroup/ostrio/blob/master/docs/prerendering/optimization.md) it will work for most of the cases without it.

And if you work on open source project [we will let you use it for free](https://ostr.io/info/built-by-developers-for-developers#free-for-opensource-community) otherwise we have a lot of ways to get discount. And honestly... it won't cost you more than a cup of coffee per month.

**Comment by nicooprat** [comment]
Interesting to see how the component approach fails in this kind of scenario. I’ll make some tests with waitOn and try to use it only when prerendering. 

In fact I first thought to use Ostrio before seeing all your packages and tried to make it all by myself. I was just wondering if it manages this kind of issue. I’ll try it for sure! 

Thanks for your time.

**Comment by dr-dimitru** [comment]
What don't you like about `waitOn` ?

**Comment by nicooprat** [comment]
I did my best to follow best practices and subscribe at component level to not block renderering. Doing so to make the app feel faster overall, and the code easier to manage. Won’t waitOn make all of this useless?

**Comment by dr-dimitru** [comment]
`waitOn` is non-blocking, there is [`whileWaiting` hook](https://github.com/VeliovGroup/flow-router#whilewaiting-hook) to show something like `loading...` sign to the user while subs and files being pulled from server. [Here is the good example](https://github.com/VeliovGroup/Meteor-Files-Demos/blob/master/demo/imports/client/router/routes.js#L114)

**Comment by nicooprat** [comment]
Thanks for the example. Looks like it would double the work and reduce the user experience with regular loading screens though...

**Comment by dr-dimitru** [comment]
> it would double the work

Not sure...

> and reduce the user experience with regular loading screens

Again, controversial...


Most of our project are using it, don't see any negative feedback, few examples:
 - [files.veliov.com](https://files.veliov.com)
 - [veliovgroup.com](https://veliovgroup.com)
 - [ostr.io](https://ostr.io)
 - [uniq.site](https://uniq.site)

**Comment by nicooprat** [comment]
Your examples load really fast so I don't even see any loading page, but in my case there could be on some stories. So I guess you can either have a loading screen shown in every whileWaiting, or create a specific loading state for every page for a better UX (like Facebook or Medium do). With component subscriptions, each one is shown has soon as its own datas are available. That's still a bit more pleasant.

Anyway I think I will try your prerendering service for now (I'm also interested in other services you offer btw), but some day I will try a different approach for the routing like what you're proposing. It would also be useful for `fastrender` (had to disable it for now as it's incompatible with `appcache`, which I want to keep as long as service workers aren't supported well enough (Safari...)). So I might come back in 2018 with these issues :)

**Comment by dr-dimitru** [comment]
> Your examples load really fast so I don't even see any loading page

May be only at ostr.io, all others is super lightweight.

> I'm also interested in other services you offer 

Kick our support team if you will have any questions.

> So I guess you can either have a loading screen shown in every whileWaiting

`whileWaiting` isn't only capable to render an intermediate template, you can simply call for overlay to show up, and hide it in `endWaiting` hook. Or you can come up with your own idea :)

> It would also be useful for `fastrender`

I was always skeptical about SSR and `fastrender`. In my experience back at the beginning of 2016, it made us slower on high-load (~350.000 daily views). I mean if something became slightly faster in one place, somewhere on the other end you will pay for it.

> So I might come back in 2018 with these issues

👍 

I'll close it for now.
Feel free to reopen it at anytime :)
