### ISSUE TITLE
is SSR working?

### ISSUE THREAD

**Issue by achtan** [VeliovGroup/Meteor-flow-router-meta#7]
hi, is it possible to ensure ssr with this package?

**Comment by dr-dimitru** [comment]
Hello @achtan ,

Please follow https://github.com/VeliovGroup/flow-router/issues/10

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
//cc @mksh-su
