### ISSUE TITLE
eslint complains about "Do not use 'new' for side effects"

### ISSUE THREAD

**Issue by floek** [VeliovGroup/Meteor-flow-router-meta#8]
### ESLint doesn't like "new" 

I initialize FlowRouterMeta:
`new FlowRouterMeta(FlowRouter);
new FlowRouterTitle(FlowRouter);` 

Then eslint complains about it:

> error  Do not use 'new' for side effects        no-new

Is there an other way to do this?

Thank you!

**Comment by dr-dimitru** [comment]
Hello @floek ,

Don't worry about it, just a warning. If it's too annoying for you simply assign it to some var:
```js
const frPlugins = {
  meta: new FlowRouterMeta(FlowRouter),
  title: new FlowRouterTitle(FlowRouter)
};
```

It may warn you what `frPlugins` defined, but not used :)

**Comment by dr-dimitru** [comment]
Hello @floek ,

Could we close this one?
//cc @mksh-su

**Comment by floek** [comment]
Hi,

yes thanks.

floek
