### ISSUE TITLE
import { Template } from 'meteor/templating' is not working

### ISSUE THREAD

**Issue by hacknlove** [VeliovGroup/Meteor-flow-router-meta#9]
`import { Template } from 'meteor/templating'`is not working since last meteor versión

[templating.tar.gz](https://github.com/VeliovGroup/Meteor-flow-router-meta/files/1673102/templating.tar.gz)

You'll see the error `TypeError: Template is undefined` unless you do `meteor remove ostrio:flow-router-extra`

**Comment by dr-dimitru** [comment]
Hello @hacknlove ,

 1. Have you installed `templating` package?
 2. Where this error is coming from? *It isn't used in this package, nor in `flow-router-extra`*
 3. You're referring to package `ostrio:flow-router-extra`, but this is repository of `ostrio:flow-router-meta`
 4. Please update this thread following our [issue template](https://github.com/VeliovGroup/Meteor-flow-router-meta/blob/master/.github/ISSUE_TEMPLATE):
     - Give an expressive description of what is went wrong
     - Version of `flow-router-meta` you're experiencing this issue
     - Version of `Meteor` you're experiencing this issue
     - Browser name and its version (Chrome, Firefox, Safari, etc.)?
     - Platform name and its version (Win, Mac, Linux)?
     - If you're getting an error or exception, please provide its full stack-trace as plain-text or screenshot

//cc @mksh-su

**Comment by hacknlove** [comment]
sorry, This is not the right repo

**Comment by dr-dimitru** [comment]
@hacknlove would you reopen it at the right repo?
